### PR TITLE
updated regex to match essid containing - and !

### PR DESCRIPTION
**Pull request by 6661620a**
AVMs Fritz!Box comes with "!" character in its essid by default. I saw some of those and others containing "-". Updated the regex to include those names

### CODE REVIEW

**Review by staz0t — CHANGES_REQUESTED** [review]
The correct regex will be
[-a-zA-Z0-9_ !]+

**Comment by staz0t** [comment]
Hey, I just noticed an error in your regex and also in my current regex.
In my current regex I didn't have to add single quotes for the space.
And in your regex, you've added '-' which in regex means any character between the charset ' and '. Which means that you've add a single quote to the regex.

So I've requested for changes

**Comment by 6661620a** [comment]
> The correct regex will be
> [-a-zA-Z0-9_ !]+

that was it :-) now it works as expected for me

**Comment by staz0t** [comment]
Thanks for contributing!

**Pull request merged**
